apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          imagePullPolicy: Always
          image: cncamp/httpserver:v1.0-metrics
          resources:
          requests:
            cpu: 100m
            memory: 100Mi
          ports:
            - containerPort: 80
